"""
e_apply_full_calibration.py
============================
STEP E -- Apply the full calibration to apple run raw frames.

Applies TWO layers of correction:
  Layer 1: Illumination map  -- corrects spatial non-uniformity
  Layer 2: Per-run scale factor -- corrects lamp level at time of run

Formula per pixel:
  Reflectance = ((Raw - Dark) / IlluminationMap) * 0.75 * ScaleFactor

Reads from:
  apple_runs/<RUN>/raw_frames/ch1/   raw apple frames
  apple_runs/<RUN>/raw_frames/ch2/
  apple_runs/<RUN>/raw_frames/ch3/
  apple_runs/<RUN>/scale_factors.json  (generated by d_per_run_panel.py)
  calibration_results/illumination_map_ch*.npy
  calibration_results/dark_avg_ch*.npy

Outputs to:
  apple_runs/<RUN>/calibrated/ch1/frame_XXXXXX.npy   float32 reflectance 0-1
  apple_runs/<RUN>/calibrated/ch2/frame_XXXXXX.npy
  apple_runs/<RUN>/calibrated/ch3/frame_XXXXXX.npy
  apple_runs/<RUN>/calibrated/ch1_rgb/frame_XXXXXX.npy  per-channel RGB (H,W,3)
  apple_runs/<RUN>/calibration_stats.csv
  apple_runs/<RUN>/calibration_summary.txt

Usage:
  python e_apply_full_calibration.py --run run_001
  python e_apply_full_calibration.py --run run_001 --no-scale  (skip scale factor)
"""

import argparse
import csv
import json
import numpy as np
from pathlib import Path
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

CAL_DIR  = Path(r'S:\MSU_Research\apple_class\calibration_results_02')
RUNS_DIR = Path(r'S:\MSU_Research\apple_class\formal_runs')
PANEL    = 0.75

# ── EXPOSURE NOTE ─────────────────────────────────────────────────────────────
# The exposure ratio (EXP_WHITE / EXP_APPLE) is already baked into the
# scale_factor computed by c_per_run_panel.py. This script requires no
# additional exposure correction -- the formula is:
#
#   refl = (raw - dark) / illum_map * PANEL * scale_factor
#
# where scale_factor = (lamp_correction) x (EXP_WHITE / EXP_APPLE)
# so the full physics is:
#   refl = (raw - dark) / illum_map * PANEL * lamp_corr * (exp_white / exp_apple)
#
# ch1 (RGB): exp_white=2500us, exp_apple=5000us, ratio=0.5
# ch2 (NIR1): exp_white=1800us, exp_apple=1800us, ratio=1.0
# ch3 (NIR2): exp_white=2300us, exp_apple=2300us, ratio=1.0

ch_names = {'ch1': 'RGB', 'ch2': 'NIR1', 'ch3': 'NIR2'}

def to_gray(arr):
    arr = np.array(arr, dtype=np.float32)
    return arr.mean(axis=2) if arr.ndim == 3 else arr

# ── Args ─────────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser(description='Apply full calibration to apple run.')
parser.add_argument('--run',      required=True, help='Run name, e.g. run_001')
parser.add_argument('--no-scale', action='store_true', help='Skip per-run scale factor (use illumination map only)')
args = parser.parse_args()

run_dir = RUNS_DIR / args.run

print('=' * 65)
print(f'  STEP D -- APPLY FULL CALIBRATION')
print(f'  Run: {args.run}')
print('=' * 65)
print()

# ── Load calibration maps ─────────────────────────────────────────────────────

print('  Loading calibration maps...')
dark_g  = {}
dark_rgb = {}
illum   = {}

for ch in ['ch1', 'ch2', 'ch3']:
    d = np.load(CAL_DIR / f'dark_avg_{ch}.npy').astype(np.float32)
    i = np.load(CAL_DIR / f'illumination_map_{ch}.npy').astype(np.float32)
    dark_g[ch]  = to_gray(d)
    illum[ch]   = to_gray(i)
    if ch == 'ch1':
        dark_rgb['ch1'] = d if d.ndim == 3 else np.stack([d, d, d], axis=2)
    print(f'    {ch_names[ch]}: illum center = {illum[ch][illum[ch].shape[0]//2, illum[ch].shape[1]//2]:.1f} DN')

# ── Load per-run scale factors ────────────────────────────────────────────────

scale_factors = {'ch1': 1.0, 'ch2': 1.0, 'ch3': 1.0}

if not args.no_scale:
    sf_path = run_dir / 'scale_factors.json'
    if sf_path.exists():
        with open(sf_path) as f:
            sf_data = json.load(f)
        scale_factors = {ch: sf_data['scale_factors'].get(ch, 1.0) for ch in ['ch1','ch2','ch3']}
        print()
        print('  Per-run scale factors:')
        for ch in ['ch1','ch2','ch3']:
            print(f'    {ch_names[ch]}: {scale_factors[ch]:.5f}  '
                  f'(corrects {(scale_factors[ch]-1)*100:+.2f}% lamp offset)')
    else:
        print()
        print('  WARNING: scale_factors.json not found. Using scale=1.0 (no scale correction).')
        print('  Run d_per_run_panel.py first for best accuracy.')
else:
    print()
    print('  Scale factor skipped (--no-scale flag).')

print()

# ── Process frames ────────────────────────────────────────────────────────────

stats_rows = []
summary = {ch: {'reflectances': []} for ch in ['ch1','ch2','ch3']}

for ch in ['ch1', 'ch2', 'ch3']:
    raw_dir = run_dir / 'raw_frames' / ch
    out_dir = run_dir / 'calibrated' / ch
    out_dir.mkdir(parents=True, exist_ok=True)

    frames = sorted(raw_dir.glob('*.jpg')) + sorted(raw_dir.glob('*.png'))
    if not frames:
        print(f'  {ch_names[ch]}: no raw frames in {raw_dir}')
        continue

    # Per-channel RGB output (ch1 only)
    if ch == 'ch1':
        out_rgb_dir = run_dir / 'calibrated' / 'ch1_rgb'
        out_rgb_dir.mkdir(parents=True, exist_ok=True)

    scale = scale_factors[ch]
    sf    = scale_factors[ch]

    print(f'  Processing {ch_names[ch]}: {len(frames)} frames...')

    for i, fpath in enumerate(frames):
        raw = np.array(Image.open(fpath)).astype(np.float32)

        # Grayscale calibration (all channels)
        raw_g = to_gray(raw)
        net_g = np.clip(raw_g - dark_g[ch], 0, None)
        refl_g = np.clip(net_g / np.clip(illum[ch], 1, None) * PANEL * sf, 0, 1)

        out_name = fpath.stem + '.npy'
        np.save(out_dir / out_name, refl_g.astype(np.float32))

        # Per-channel RGB calibration (ch1 only)
        if ch == 'ch1' and raw.ndim == 3:
            dr = dark_rgb['ch1'][:raw.shape[0], :raw.shape[1]]
            # illum map is grayscale, broadcast to 3 channels
            illum_3  = np.stack([illum[ch]] * 3, axis=2)
            net_rgb  = np.clip(raw - dr, 0, None)
            refl_rgb = np.clip(net_rgb / np.clip(illum_3, 1, None) * PANEL * sf, 0, 1)
            np.save(out_rgb_dir / out_name, refl_rgb.astype(np.float32))

        # Stats
        H, W = refl_g.shape
        cen  = refl_g[H*2//5:H*3//5, W*2//5:W*3//5].mean()
        summary[ch]['reflectances'].append(float(cen))

        if i == 0 or (i + 1) % 50 == 0 or i == len(frames) - 1:
            print(f'    Frame {i+1:>4}/{len(frames)}: center refl = {cen:.4f}')

    print()

# ── Save stats CSV ────────────────────────────────────────────────────────────

stats_path = run_dir / 'calibration_stats.csv'
with open(stats_path, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['frame', 'ch1_refl', 'ch2_refl', 'ch3_refl'])
    n = max(len(summary[ch]['reflectances']) for ch in ['ch1','ch2','ch3'])
    for i in range(n):
        row = [i + 1]
        for ch in ['ch1', 'ch2', 'ch3']:
            v = summary[ch]['reflectances']
            row.append(f'{v[i]:.5f}' if i < len(v) else '')
        writer.writerow(row)

# ── Summary ───────────────────────────────────────────────────────────────────

summary_lines = [
    f'CALIBRATION SUMMARY -- {args.run}',
    '=' * 50,
    f'Scale factors applied: {not args.no_scale}',
    '',
]
for ch in ['ch1', 'ch2', 'ch3']:
    v = np.array(summary[ch]['reflectances'])
    if len(v) == 0:
        continue
    variation = (v.max() - v.min()) / v.mean() * 100 if v.mean() > 0 else 0
    summary_lines += [
        f'{ch_names[ch]}:',
        f'  Frames:      {len(v)}',
        f'  Mean refl:   {v.mean():.4f}',
        f'  Std:         {v.std():.4f}',
        f'  Min:         {v.min():.4f}',
        f'  Max:         {v.max():.4f}',
        f'  Variation:   {variation:.2f}%',
        f'  Scale factor: {scale_factors[ch]:.5f}',
        '',
    ]

summary_path = run_dir / 'calibration_summary.txt'
with open(summary_path, 'w') as f:
    f.write('\n'.join(summary_lines))

print('-' * 65)
print(f'  Calibrated frames saved to: {run_dir / "calibrated"}')
print(f'  Stats CSV:    {stats_path.name}')
print(f'  Summary:      {summary_path.name}')
print()
print('  CALIBRATION COMPLETE.')
print('  Calibrated reflectance .npy files are ready for model training.')
print('=' * 65)
